/** Composer chrome + view-model return (F9 P2). */
import { useMemo } from "react";
import { useRoomComposerPopovers } from "./useRoomComposerPopovers";
import { useRoomComposerEventStack } from "./useRoomComposerEventStack";
import { useAutonomySession } from "./useAutonomySession";
import { useRoomPaletteActions } from "./useRoomPaletteActions";
import { buildPlanMetaView } from "../utils/planMeta";
import { DEMO_PLAN_STALE_NOTICE } from "../utils/tweaksDemoFixtures";
import type { useRoomChatBootstrap } from "./useRoomChatBootstrap";
import type { useRoomChatInteractions } from "./useRoomChatInteractions";

type Ctx = ReturnType<typeof useRoomChatBootstrap> & ReturnType<typeof useRoomChatInteractions>;

export function useRoomChatPresentation(ctx: Ctx) {
  const { props } = ctx;
  const {
    session,
    sessionId,
    onOpenSettings,
    sidebarOpen,
    onToggleSidebar,
    loading,
    healthAgents = [],
    agents,
  } = props;
  const {
    isNew,
    selected,
    inboxReloadKey,
    tweaks,
    composerPlanStale,
    slashCommands,
    setWorkspaceTab,
    running,
    handleStop,
    handleReleaseRunLock,
    openTranscriptTab,
    setText,
    turnProfile,
    composerModeVariant,
    authRun,
    setAuthRun,
    secretCommand,
    secretValue,
    setSecretCommand,
    setSecretValue,
    commandChoices,
    commandChoiceIndex,
    setCommandChoiceIndex,
    commandScopeChoices,
    setCommandScopeChoices,
    commandMultiChoices,
    setCommandMultiChoices,
    multiSelected,
    setMultiSelected,
    modelPopover,
    setModelPopover,
    setCommandChoices,
    setCommandHint,
    executeSlashCommand,
    handleAuthRunComplete,
    applySessionScopedModels,
    planMd,
    workFocus,
    setWorkFocus,
    synthesizing,
    runBusy,
    executeBusy,
    handleSynthesizeNow,
    transcript,
    focusObjection,
    refreshSessionMeta,
    roomTasks,
    planExecute,
    planWorkflow,
    showPlanApproval,
    verifiedLoopBusy,
    verifiedLoopError,
    handleVerifiedApprove,
    handleVerifiedReject,
    workHookAlert,
    setWorkHookAlert,
    inboxPendingCount,
    handleInboxResolved,
    handleInboxBuildStarted,
    handleInboxRefClick,
    execPendingForBar,
    demoExecPending,
    showExecuteQueueStrip,
    consensusForBar,
    showConsensusDryRunGate,
    consensusGateBusy,
    handleConsensusDryRun,
    dismissConsensusProposal,
    openDiffTab,
    openFilesTab,
    openFileInWorkbench,
    pushMacNotification,
    locale,
    toggleInspector,
    handleSelectRightPanelMode,
    setWorkbenchMenuOpen,
    avoidWorkbenchNotice,
    discussPaused,
    decisionRuntime,
    verifiedLoopView,
    consensusBlocked,
    planWorkflowPlanIntent,
    showPlanWorkflowBanner,
    showPlanWorkflowComposerHint,
    recoveryVisible,
    recoveryLifecycleView,
    recoveryBusyAction,
    releasingLock,
    discussRecoveryBusy,
    composerNoticeDismissed,
    setComposerNoticeDismissed,
    openHumanInbox,
    openWorkApproval,
    handleRecoveryAction,
    handleRecoveryRetryAction,
    setRecoveryDismissedSig,
    recoverySignature,
    runStartedAt,
    localeMsg,
    handleNotificationOpen,
    clarifierQuestions,
    clarifierInterview,
    planWorkflowActive,
    longRunning,
    sendReceipt,
    sendReceiptRaw,
    composerInputLocked,
    composerSendLocked,
    composerPlaceholder,
    pendingFiles,
    addFiles,
    setPendingFiles,
    composerObjectionNotice,
    composerEmergenceHint,
    composerPresetHint,
    composerCostHint,
    visiblePresets,
    roomPreset,
    selectRoomPreset,
    runSlashCommand,
    commandHint,
    externalCommandConfirm,
    setExternalCommandConfirm,
    permOpen,
    setPermOpen,
    pendingSend,
    setPendingSend,
    executeSend,
    composeMode,
    goalView,
    planExecutions,
    filesFocusPath,
    filesFocusRevision,
    workbenchPanelWidth,
    setActiveWorkbenchWidth,
    commitWorkbenchWidth,
    rightPanelMode,
    inspectorOpen,
    handleSend,
    firstOpenBlock,
    readiness,
    text,
    recoveryItems: recoveryItemsList,
  } = ctx;

  const { modelPopoverNode, authPopover, authPickerPopover, choicePopover } =
    useRoomComposerPopovers({
      sessionId,
      authRun,
      setAuthRun,
      secretCommand,
      secretValue,
      setSecretValue,
      setSecretCommand,
      commandChoices,
      commandChoiceIndex,
      setCommandChoiceIndex,
      commandScopeChoices,
      setCommandScopeChoices,
      commandMultiChoices,
      setCommandMultiChoices,
      multiSelected,
      setMultiSelected,
      modelPopover,
      setModelPopover,
      setCommandChoices,
      setCommandHint,
      executeSlashCommand,
      handleAuthRunComplete,
      applySessionScopedModels,
    });

  const title = isNew ? "Session" : session?.topic || sessionId || "Session";
  const {
    view: autonomyView,
    loading: autonomyLoading,
    changing: autonomyChanging,
    setLevel: setAutonomyLevel,
  } = useAutonomySession({
    sessionId,
    sessionRun: session?.run as Record<string, unknown> | undefined,
    reloadKey: inboxReloadKey,
  });
  const titleMeta =
    !isNew || selected.length > 0
      ? `${selected.length} ${selected.length === 1 ? "agent" : "agents"}`
      : undefined;

  const planMeta = buildPlanMetaView(session?.run);
  const workPlanStaleNotice = tweaks.planStaleDemo
    ? DEMO_PLAN_STALE_NOTICE
    : composerPlanStale;
  const currentPlanRevision =
    planMeta.lastUpdate?.completed_at || planMeta.lastUpdate?.ts || null;

  const paletteActions = useRoomPaletteActions({
    slashCommands,
    setWorkspaceTab,
    running,
    handleStop,
    handleReleaseRunLock,
    onOpenSettings,
    openTranscriptTab,
    setText,
  });

  const composerClassName = useMemo(
    () =>
      [
        turnProfile === "review" ? "composer--review" : undefined,
        turnProfile === "loop" ? "composer--free" : undefined,
        composerModeVariant === "consensus"
          ? "composer--consensus-mode"
          : undefined,
        composerModeVariant === "plan" ? "composer--plan-mode" : undefined,
        composerModeVariant === "discuss"
          ? "composer--discuss-mode"
          : undefined,
      ]
        .filter(Boolean)
        .join(" ") || undefined,
    [turnProfile, composerModeVariant],
  );

  const composerEventStack = useRoomComposerEventStack({
    sessionId,
    session,
    planMd,
    planMeta,
    workPlanStaleNotice,
    workFocus,
    setWorkFocus,
    synthesizing,
    running,
    runBusy,
    executeBusy,
    handleSynthesizeNow,
    handlePlanRefClick: transcript.handlePlanRefClick,
    focusTask: transcript.focusTask,
    focusObjection,
    refreshSessionMeta,
    roomTasks,
    agents,
    planExecute,
    planWorkflow,
    showPlanApproval,
    verifiedLoopBusy,
    verifiedLoopError,
    handleVerifiedApprove,
    handleVerifiedReject,
    workHookAlert,
    setWorkHookAlert,
    inboxPendingCount,
    inboxReloadKey,
    currentPlanRevision,
    handleInboxResolved,
    handleInboxBuildStarted,
    handleInboxRefClick,
    execPendingForBar,
    demoExecPending,
    showExecuteQueueStrip,
    consensusForBar,
    showConsensusDryRunGate,
    consensusGateBusy,
    consensusGateDemo: tweaks.consensusGateDemo,
    setConsensusGateDemo: tweaks.setConsensusGateDemo,
    handleConsensusDryRun,
    dismissConsensusProposal,
    openDiffTab,
    openFilesTab,
    openFileInWorkbench,
    pushMacNotification,
  });

  return {

    paletteActions,
    title,
    titleMeta,
    autonomyView,
    autonomyLoading,
    autonomyChanging,
    setAutonomyLevel,
    inspectorOpen,
    rightPanelMode,
    locale,
    toggleInspector,
    handleSelectRightPanelMode,
    setWorkbenchMenuOpen,
    isNew,
    sessionId,
    avoidWorkbenchNotice,
    inboxPendingCount,
    inboxReloadKey,
    discussPaused,
    decisionRuntime,
    showPlanApproval,
    verifiedLoopPendingApproval: verifiedLoopView.pendingApproval,
    firstOpenBlock,
    consensusBlocked,
    planWorkflow,
    planWorkflowPlanIntent,
    showPlanWorkflowBanner,
    showPlanWorkflowComposerHint,
    recoveryVisible,
    recoveryLifecycleView,
    recoveryBusyActionId:
      recoveryBusyAction ??
      (releasingLock ? "release_lock" : null) ??
      (discussRecoveryBusy ? "run_discuss_recovery" : null),
    composerNoticeDismissed,
    setComposerNoticeDismissed,
    openHumanInbox,
    openWorkApproval,
    handleRecoveryAction,
    handleRecoveryRetryAction,
    setRecoveryDismissedSig,
    recoverySignature,
    transcript,
    runStartedAt,
    localeMsg,
    tweaks,
    handleNotificationOpen,
    composerEventStack,
    running,
    runBusy,
    readiness,
    healthAgents,
    selected,
    clarifierQuestions,
    clarifierInterview,
    planWorkflowActive,
    longRunning,
    handleStop,
    sendReceipt,
    sendReceiptRaw,
    composerClassName,
    text,
    setText,
    handleSend,
    slashCommands,
    runSlashCommand,
    composerInputLocked,
    composerSendLocked,
    composerPlaceholder,
    pendingFiles,
    addFiles,
    setPendingFiles,
    composerObjectionNotice,
    focusObjection,
    composerEmergenceHint,
    composerPresetHint,
    composerCostHint,
    visiblePresets,
    roomPreset,
    selectRoomPreset,
    agents,
    executeSlashCommand,
    commandHint,
    choicePopover,
    authPopover,
    authPickerPopover,
    modelPopoverNode,
    externalCommandConfirm,
    setExternalCommandConfirm,
    permOpen,
    setPermOpen,
    pendingSend,
    setPendingSend,
    executeSend,
    composeMode,
    loading,
    recoveryItemsLength: recoveryItemsList.length,
    goalView,
    planMeta,
    planExecutions,
    filesFocusPath,
    filesFocusRevision,
    workbenchPanelWidth,
    setActiveWorkbenchWidth,
    commitWorkbenchWidth,
    session,
    onOpenSettings,
    sidebarOpen,
    onToggleSidebar,
  };
}
