"""Trimmed room context for agent CLI calls (not scribe).

Submodules:
- constraints — guidance constants, build_constraints_block, gate/tag extraction
- peer_digest — [이번 턴 · 동료 발화] assembly
- plan_excerpt — plan.md bullet extraction
- message_trim — thread trim, scribe block, recent-turns header
"""

from __future__ import annotations

from agent_lab.consensus_agreements import (
    agreement_sync_failed_notice,
    pending_consensus_agreements,
)
from agent_lab.room.context._shared import MessageLike, _MessageLike, env_bool as _env_bool
from agent_lab.room.context.constraints import (
    AGENT_CONNECT_HINT,
    ANALYSIS_TURN_GUIDANCE,
    CLAUDE_TOOL_RULES,
    CODEX_TOOL_RULES,
    CONVERSATION_GUIDANCE,
    CURSOR_TOOL_RULES,
    EFFICIENCY_RESPONSE_GUIDANCE,
    FAST_TURN_GUIDANCE,
    KIMI_WORK_FAST_TOOL_RULES,
    KIMI_WORK_TOOL_RULES,
    MULTI_AGENT_COORDINATION,
    PEER_DECISION_GUIDANCE,
    REPLY_FORMAT_RULES,
    agent_tool_rules,
    build_constraints_block,
    extract_human_gates,
    extract_status_tags,
    is_no_objection_response,
    is_pass_response,
    is_pure_no_objection,
)
from agent_lab.room.context.message_trim import (
    _compact_tool_output_enabled,
    _split_human_turns,
    _tool_output_char_cap,
    _truncate_fenced_blocks,
    _truncate_old_tool_outputs,
    agent_thread_formatter,
    build_recent_turns_block,
    cap_ephemeral_system_messages,
    cap_pinned_messages,
    compact_current_turn_pins,
    count_messages,
    current_turn_message_count,
    format_agent_numbered_thread,
    format_thread_numbered_slice,
    pinned_current_turn_messages,
    prepare_recent_messages,
    recent_messages_by_turns,
    scribe_thread_block,
    trim_messages_by_chars,
    trim_messages_by_chars_pinned,
)
from agent_lab.room.context.peer_digest import (
    build_peer_round_block,
    build_turn_bridge_block,
    collect_peer_messages,
    collect_r1_turn_replies,
    dedupe_peer_from_recent,
    format_peer_block,
)
from agent_lab.room.context.plan_excerpt import (
    build_plan_open_block,
    extract_agreed_bullets,
    extract_open_bullets,
    plan_stale_banner,
    section_body as _section_body,
    split_plan_sections as _split_plan_sections,
)

__all__ = [
    "AGENT_CONNECT_HINT",
    "ANALYSIS_TURN_GUIDANCE",
    "CLAUDE_TOOL_RULES",
    "CODEX_TOOL_RULES",
    "CONVERSATION_GUIDANCE",
    "CURSOR_TOOL_RULES",
    "EFFICIENCY_RESPONSE_GUIDANCE",
    "FAST_TURN_GUIDANCE",
    "KIMI_WORK_FAST_TOOL_RULES",
    "KIMI_WORK_TOOL_RULES",
    "MULTI_AGENT_COORDINATION",
    "MessageLike",
    "PEER_DECISION_GUIDANCE",
    "REPLY_FORMAT_RULES",
    "_MessageLike",
    "_compact_tool_output_enabled",
    "_env_bool",
    "_section_body",
    "_split_human_turns",
    "_split_plan_sections",
    "_tool_output_char_cap",
    "_truncate_fenced_blocks",
    "_truncate_old_tool_outputs",
    "agreement_sync_failed_notice",
    "agent_thread_formatter",
    "agent_tool_rules",
    "build_constraints_block",
    "build_peer_round_block",
    "build_plan_open_block",
    "build_recent_turns_block",
    "build_turn_bridge_block",
    "cap_ephemeral_system_messages",
    "cap_pinned_messages",
    "collect_peer_messages",
    "collect_r1_turn_replies",
    "compact_current_turn_pins",
    "count_messages",
    "current_turn_message_count",
    "dedupe_peer_from_recent",
    "extract_agreed_bullets",
    "extract_human_gates",
    "extract_open_bullets",
    "extract_status_tags",
    "format_agent_numbered_thread",
    "format_peer_block",
    "format_thread_numbered_slice",
    "is_no_objection_response",
    "is_pass_response",
    "is_pure_no_objection",
    "pinned_current_turn_messages",
    "pending_consensus_agreements",
    "plan_stale_banner",
    "prepare_recent_messages",
    "recent_messages_by_turns",
    "scribe_thread_block",
    "trim_messages_by_chars",
    "trim_messages_by_chars_pinned",
]
