"""Default model IDs for 3-agent room (override via env)."""

DEFAULT_CURSOR_MODEL = "default"
DEFAULT_CODEX_MODEL = "gpt-5.5"
DEFAULT_CODEX_REASONING_EFFORT = "high"
DEFAULT_CODEX_ROOM_REASONING_EFFORT = "high"
DEFAULT_CODEX_ROOM_MAX_COMMANDS = 6
DEFAULT_CODEX_ROOM_IDLE_TIMEOUT_SEC = 600
DEFAULT_CLAUDE_MODEL = "opus"
DEFAULT_CLAUDE_REASONING_EFFORT = "high"
